# Generated by Django 4.1.7 on 2023-04-01 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='board_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('writer', models.ForeignKey(db_column='writer', on_delete=django.db.models.deletion.CASCADE, to='myApp.user_tbl')),
            ],
        ),
    ]
