# Generated by Django 4.1.7 on 2023-04-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_board_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_tbl',
            fields=[
                ('city_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city_lat', models.FloatField(default=0.0)),
                ('city_lng', models.FloatField(default=0.0)),
            ],
        ),
    ]
