# Generated by Django 4.1.7 on 2023-04-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_weather_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='combination_tbl',
            fields=[
                ('combination', models.IntegerField(primary_key=True, serialize=False)),
                ('outer', models.CharField(max_length=50)),
                ('torso', models.CharField(max_length=50)),
                ('pants', models.CharField(max_length=50)),
                ('shoes', models.CharField(max_length=50)),
                ('Highest_temperature', models.FloatField(default=0)),
                ('Lowest_temperature', models.FloatField(default=0)),
            ],
        ),
    ]
